import process from 'node:process';
import { spawn } from 'node:child_process';
import { createWriteStream, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const dir=process.env.SPATIAL_QA_OUTPUT;
if(!dir)throw new Error('Missing QA output directory');
mkdirSync(dir,{recursive:true});
const log=createWriteStream(join(dir,'preview.log'),{flags:'a'});
const startedAt=new Date().toISOString();
const child=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4186','--strictPort'],{stdio:['ignore','pipe','pipe']});
const stdout=createWriteStream(join(dir,'webserver.stdout.log'));
const stderr=createWriteStream(join(dir,'webserver.stderr.log'));
writeFileSync(join(dir,'server-process.json'),JSON.stringify({startedAt,pid:child.pid,command:[process.execPath,'node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4186','--strictPort'],cwd:process.cwd()},null,2));
for(const [stream,target,file] of [[child.stdout,process.stdout,stdout],[child.stderr,process.stderr,stderr]])stream.on('data',data=>{log.write(data);file.write(data);target.write(data);});
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>child.kill(signal));
child.on('error',error=>{log.end(error.message);process.exitCode=1;});
child.on('exit',(code,signal)=>{log.end();stdout.end();stderr.end();writeFileSync(join(dir,'server-exit.json'),JSON.stringify({pid:child.pid,code,signal,endedAt:new Date().toISOString()},null,2));process.exitCode=code??1;});
