import {test,expect} from './live-fixture';
import {liveApi,SYNTHETIC_PIN} from './support/live-api';
import type {Page} from '@playwright/test';
let api:Awaited<ReturnType<typeof liveApi>>;
test.beforeEach(async({page})=>{
 api=await liveApi();
 await page.route('https://math-e2e.invalid/functions/v1/*',async route=>{const req=route.request();const response=await api.request(req.url(),req.postDataJSON(),req.headers()['x-student-token']);await route.fulfill({status:response.status,body:await response.text(),contentType:'application/json'});});
 await page.goto('/?class=QAONLY');await page.getByLabel('이름',{exact:true}).fill('QA학생1');await page.getByLabel('PIN 4자리').fill(SYNTHETIC_PIN);await page.getByRole('button',{name:'들어가기',exact:true}).click();await expect(page.getByRole('heading',{name:'공간과 입체 월드',exact:true})).toBeVisible();
});
test.afterEach(async()=>{await api.close();});
async function open(page:Page,n:number,kind:string){
 await page.goto(`/lesson/${n}/learn`);await expect(page.locator('[data-guided-kind]')).toHaveAttribute('data-guided-kind',kind);
 await expect(page.getByText('블록을 자유롭게 놓아 보고, 보기 버튼으로 관찰 위치를 바꾸어 보세요.',{exact:false})).toHaveCount(0);
}
async function place(page:Page,x=1,z=1){
 if(!await page.getByLabel('가로',{exact:true}).isVisible())await page.getByText('버튼으로 놓기',{exact:true}).click();
 await page.getByLabel('가로',{exact:true}).fill(String(x));await page.getByLabel('세로',{exact:true}).fill(String(z));await page.getByRole('button',{name:'쌓기',exact:true}).click();
}
async function capture(page:Page,n:number){await expect(page.getByText('3D 화면을 열 수 없어요.',{exact:false})).toHaveCount(0);await page.screenshot({path:`test-results/guided-lesson-${n}.png`,fullPage:true});}

test('L1 build, predict and count',async({page})=>{await open(page,1,'count');await place(page);await page.getByLabel('먼저 센 개수').fill('6');await page.getByRole('button',{name:'개수 비교',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'실제 6개'})).toBeVisible();await capture(page,1);});
test('L2 observe fixed shape in five directions',async({page})=>{await open(page,2,'viewpoints');for(const [label,value] of [['앞에서 보기','앞'],['뒤에서 보기','뒤'],['왼쪽에서 보기','왼쪽'],['오른쪽에서 보기','오른쪽'],['위에서 보기','위']]){await page.getByRole('button',{name:label,exact:true}).click();await expect(page.getByLabel('현재 관찰 시점')).toHaveText(value);}await expect(page.getByText('버튼으로 놓기',{exact:true})).toHaveCount(0);await capture(page,2);});
test('L3 direction changes both camera and projection',async({page})=>{await open(page,3,'projections');for(const [label,table,view] of [['위 모양 확인','위 투영','위'],['앞 모양 확인','앞 투영','앞'],['오른쪽 옆 모양 확인','오른쪽 옆 투영','옆(오른쪽)']]){await page.getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('table',{name:table,exact:true})).toBeVisible();await expect(page.getByLabel('현재 관찰 시점')).toHaveText(view);}await expect(page.getByRole('button',{name:'오른쪽 옆 투영 2행 1열',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'오른쪽 옆 투영 2행 3열',exact:true})).toHaveAttribute('aria-pressed','false');await capture(page,3);});
test('L4 building changes height and layer sums',async({page})=>{await open(page,4,'height-layers');await expect(page.getByText('높이 합 5 = 층별 합 5 = 전체 5',{exact:true})).toBeVisible();await place(page);await expect(page.getByText('높이 합 6 = 층별 합 6 = 전체 6',{exact:true})).toBeVisible();await expect(page.getByRole('table',{name:'3층',exact:true})).toBeVisible();await capture(page,4);});
test('L5 front-only evidence then different counts and extra information',async({page})=>{await open(page,5,'information');await expect(page.getByRole('table')).toHaveCount(1);await expect(page.locator('canvas')).toHaveCount(0);await page.getByRole('button',{name:'알 수 없다',exact:true}).click();await expect(page.getByText('모형 1: 3개 · 앞모습은 같아요.',{exact:true})).toBeVisible();const initial=await page.getByRole('table',{name:'주어진 앞모습'}).innerHTML();await page.getByRole('button',{name:'다른 가능한 입체 보기'}).click();await expect(page.getByText('모형 2: 4개 · 앞모습은 같아요.',{exact:true})).toBeVisible();expect(await page.getByRole('table',{name:'주어진 앞모습'}).innerHTML()).toBe(initial);await page.getByRole('button',{name:'높이 정보 추가'}).click();await expect(page.getByRole('table',{name:'높이 지도'})).toBeVisible();await capture(page,5);});
test('L6 actual construction satisfies conditions and explores a different valid model',async({page})=>{await open(page,6,'constraints');await page.getByRole('button',{name:'세 방향 조건 비교'}).click();await expect(page.getByText('아직 다른 모양이 있어요.',{exact:false})).toBeVisible();for(const [x,z] of [[1,1],[1,1],[2,1],[1,2],[2,2],[2,2]])await place(page,x,z);await page.getByRole('button',{name:'세 방향 조건 비교'}).click();await expect(page.getByText('세 방향 조건을 모두 만족해요.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'조건에 맞는 다른 예 보기'}).click();await expect(page.getByText('이 범위에서 최소 6개, 최대 8개예요.',{exact:false})).toBeVisible();await capture(page,6);});
test('L7 height edits construct and undo the numeric change',async({page})=>{await open(page,7,'height-edit');await page.getByRole('button',{name:'높이 지도 1행 1열 증가',exact:true}).click();await expect(page.getByLabel('탐구 블록 수')).toHaveText('현재 6개 · 3층');await page.getByRole('button',{name:'높이 지도 1행 1열 감소',exact:true}).click();await expect(page.getByLabel('탐구 블록 수')).toHaveText('현재 5개 · 2층');await capture(page,7);});
test('L8 layer edit keeps support and changes model',async({page})=>{await open(page,8,'layer-edit');await page.getByLabel('편집할 층').selectOption('1');await page.getByRole('button',{name:'2층 편집 2행 2열',exact:true}).click();await expect(page.getByText('윗층을 놓으려면 아래층이 필요해요.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'2층 편집 1행 2열',exact:true}).click();await expect(page.getByLabel('탐구 블록 수')).toHaveText('현재 6개 · 2층');await page.getByRole('button',{name:'2층 편집 1행 2열',exact:true}).click();await expect(page.getByLabel('탐구 블록 수')).toHaveText('현재 5개 · 2층');await page.getByLabel('현재 층만 보기').selectOption('2');await capture(page,8);});
test('L9 learn uses actual creator and system problem UI',async({page})=>{await open(page,9,'peer');await expect(page.getByRole('button',{name:/^기본 연습 \d+$/})).toHaveCount(24);for(let i=0;i<10;i++)await place(page,i%5+1,Math.floor(i/5)+1);await page.getByRole('button',{name:'10개 완성 → 문제 카드 고르기'}).click();await expect(page.getByRole('button',{name:'이 카드로 정하기 →'})).toBeVisible();await capture(page,9);});
test('L10 learn reuses real saved building, world route remains project',async({page})=>{await open(page,10,'architecture');await page.getByRole('textbox',{name:'건축물 이름',exact:true}).fill('탐구관');await page.getByLabel('설계 이유',{exact:true}).fill('여러 방향을 비교해요');await place(page);await page.getByRole('button',{name:'10차시 설계 저장',exact:true}).click();await expect(page.getByText('설계를 저장했어요.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'작품 활동 계속하기'}).click();await expect(page).toHaveURL(/\/lesson\/10\/project$/);await expect(page.getByRole('textbox',{name:'건축물 이름',exact:true})).toHaveValue('탐구관');await capture(page,10);});
test('L11 learn uses the same saved project for representation and explanation',async({page})=>{await open(page,10,'architecture');await page.getByRole('textbox',{name:'건축물 이름',exact:true}).fill('이어 보는 탐구관');await page.getByLabel('설계 이유',{exact:true}).fill('공간 관찰');await place(page);await page.getByRole('button',{name:'10차시 설계 저장',exact:true}).click();await expect(page.getByText('설계를 저장했어요.',{exact:true})).toBeVisible();await open(page,11,'presentation');await expect(page.getByRole('heading',{name:'이어 보는 탐구관',exact:true})).toBeVisible();await page.getByLabel('공간 이름',{exact:true}).fill('전시실');await page.getByRole('button',{name:'설계 저장',exact:true}).click();await expect(page.getByText('설계를 저장했어요.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('공간 이름',{exact:true})).toHaveValue('전시실');await capture(page,11);});
test('L12 linked representations and existing reflection save/restore',async({page})=>{await open(page,12,'connections');await page.getByRole('button',{name:'높이 지도 1행 1열 증가',exact:true}).click();await expect(page.getByLabel('탐구 블록 수')).toHaveText('현재 6개 · 3층');await page.getByRole('button',{name:'세 방향으로 보기'}).click();await expect(page.getByRole('table')).toHaveCount(3);await page.getByRole('button',{name:'층별로 보기'}).click();await expect(page.getByRole('table',{name:'3층',exact:true})).toBeVisible();await page.getByRole('textbox',{name:'배운 점',exact:true}).fill('지도는 달라도 같은 입체예요.');await page.getByRole('button',{name:'자기평가 저장',exact:true}).click();await expect(page.getByText('자기평가를 저장했어요.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('textbox',{name:'배운 점',exact:true})).toHaveValue('지도는 달라도 같은 입체예요.');await capture(page,12);});
test('invalid lesson does not silently become free build',async({page})=>{await page.goto('/lesson/13/learn');await expect(page.getByRole('heading',{name:'차시를 찾을 수 없어요.'})).toBeVisible();await expect(page.locator('canvas')).toHaveCount(0);});
