/* global process, console, URL */
// Catalog and aggregate inputs are PRIVATE, outside Git. No remote connection.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const [baselinePath, expectedPath, outputPath] = process.argv.slice(2);
if (!baselinePath || !expectedPath || !outputPath) throw new Error('Usage: node build-checks.mjs PRIVATE_BASELINE.json PRIVATE_EXPECTED.json PRIVATE_OUTPUT');
const before = JSON.parse(readFileSync(baselinePath));
const after = JSON.parse(readFileSync(expectedPath));
const sections = ['tables','columns','constraints','indexes','policies','policy_modes','column_acls','triggers','rpcs','rpc_definitions'];
const expected = value => Object.fromEntries(sections.map(key => [key,value[key]]));
const literal = value => "'" + JSON.stringify(value).replaceAll("'", "''") + "'::jsonb";
const catalog = readFileSync(new URL('./metadata-select.sql', import.meta.url),'utf8').trim().replace(/;$/, '');
const aggregate = readFileSync(new URL('./backfill-aggregate.sql', import.meta.url),'utf8').replace(/^BEGIN READ ONLY;\s*/i,'').replace(/\s*COMMIT;\s*$/i,'').trim().replace(/;$/, '');
const counts = `select jsonb_build_object(${before.tables.map(t=>`'${t.name}',(select count(*) from public."${t.name}")`).join(',')}) counts`;
const progress = `select jsonb_build_object('completed',(select count(*) from public.sb_student_progress where completed),'rows',(select count(*) from public.sb_student_progress),'by_lesson',(select coalesce(jsonb_agg(x order by lesson),'[]') from (select lesson,count(*) total,count(*) filter(where completed) completed,count(*) filter(where completed and completed_at is null) missing_completed_at from public.sb_student_progress group by lesson) x)) progress`;
const body = target => `with catalog as (${catalog}), backfill as (${aggregate}), rows as (${counts}), progress as (${progress}), expected as (select ${literal(expected(target))} value), checks as (select key,(catalog.snapshot->key)=(expected.value->key) pass,md5((catalog.snapshot->key)::text) actual_fingerprint from catalog,expected,(values ${sections.map(k=>`('${k}')`).join(',')}) s(key))`;
const header = `-- READ ONLY: catalog and aggregate counts only. No student row payloads.\n-- Database metadata does NOT prove project identity. Verify Dashboard Project ID separately.\nBEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;\nSET LOCAL statement_timeout='20s';\nSET LOCAL lock_timeout='2s';\n`;
const shared = `'captured_at',now(),'read_only',current_setting('transaction_read_only'),'identity_verification','MANUAL_DASHBOARD_REQUIRED','schema_version',catalog.snapshot->'schema_version','catalog_pass',(select bool_and(pass) from checks),'catalog_checks',(select jsonb_agg(to_jsonb(checks) order by key) from checks),'counts',rows.counts,'backfill',backfill.aggregate,'progress',progress.progress`;
const pre = header + body(before) + ` select jsonb_build_object(${shared},'history_pass',catalog.snapshot->>'schema_version'='${before.schema_version}' and catalog.snapshot->'migration_history'=${literal(before.migration_history)},'external_edge_gate','NOT_VERIFIED_BY_SQL') precheck from catalog,rows,backfill,progress;\nCOMMIT;\n`;
const baseline = `,baseline as (select $precheck$null$precheck$::jsonb value)`;
const post = header + `-- Replace ONLY null between $precheck$ delimiters with the full PRECHECK result JSON.\n-- Without a baseline, baseline_present and all_preservation_checks_pass cannot pass.\n` + body(after) + baseline + `,preservation as (select t.name,coalesce((rows.counts->>t.name)::bigint = (baseline.value->'counts'->>t.name)::bigint + case when t.name='sb_student_progress' then (baseline.value->'backfill'->>'required_inserts')::bigint+(baseline.value->'backfill'->>'activity_inserts')::bigint else 0 end,false) pass from rows,baseline,(values ${before.tables.map(t=>`('${t.name}')`).join(',')}) t(name))
select jsonb_build_object(${shared},'baseline_present',coalesce(baseline.value->>'read_only'='on' and baseline.value->>'catalog_pass'='true' and baseline.value->>'history_pass'='true',false),'history_pass',catalog.snapshot->>'schema_version'='${before.schema_version}' and catalog.snapshot->'migration_history'=${literal(before.migration_history)},'row_count_checks',(select jsonb_agg(to_jsonb(preservation) order by name) from preservation),'all_preservation_checks_pass',(select bool_and(pass) from preservation),'backfill_remaining_zero',(backfill.aggregate->>'total_changed_rows')::bigint=0,'completed_total_pass',coalesce((progress.progress->>'completed')::bigint=(baseline.value->'progress'->>'completed')::bigint+(baseline.value->'backfill'->>'required_inserts')::bigint+(baseline.value->'backfill'->>'required_false_to_true')::bigint+(baseline.value->'backfill'->>'activity_completed_inserts')::bigint+(baseline.value->'backfill'->>'activity_promotions')::bigint,false),'data_content_check','COUNTS_ONLY; no row payloads read/exported') postcheck from catalog,rows,backfill,progress,baseline;\nCOMMIT;\n`;
mkdirSync(outputPath,{recursive:true});
writeFileSync(outputPath+'/PRECHECK.sql',pre);writeFileSync(outputPath+'/POSTCHECK.sql',post);
console.log('Generated PRECHECK and POSTCHECK. Actual execution NOT performed.');
