/* global process, console, Request */
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import {createFixture,snapshot,catalog}from'./fixture.mjs';import{client}from'./adapter.mjs';
const T='11111111-1111-4111-8111-111111111111', U='22222222-2222-4222-8222-222222222222', C='33333333-3333-4333-8333-333333333333',D='44444444-4444-4444-8444-444444444444';
const S=['55555555-5555-4555-8555-555555555551','55555555-5555-4555-8555-555555555552','55555555-5555-4555-8555-555555555553','55555555-5555-4555-8555-555555555554'];
const P=['66666666-6666-4666-8666-666666666661','66666666-6666-4666-8666-666666666662','66666666-6666-4666-8666-666666666663'];
const db=await createFixture();globalThis.__deltaClient=client(db);globalThis.__deltaTeachers=new Map([['Bearer SYNTHETIC_OWNER',T],['Bearer SYNTHETIC_OTHER',U]]);let served;globalThis.Deno={env:{get:k=>k==='APP_SESSION_SECRET'?'local-fixture-only-secret-20261003':undefined},serve:h=>served=h};
const security=await import('./supabase/functions/_shared/security.ts');await import('./supabase/functions/student-auth/index.ts');const auth=served;await import('./supabase/functions/student-api/index.ts');const api=served;
async function req(handler,body,headers={}){const response=await handler(new Request('http://synthetic.invalid',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)}));return{status:response.status,body:await response.json()};}
const tests=[];async function check(name,fn){try{await fn();tests.push({name,status:'PASS'});console.log('PASS',name);}catch(e){tests.push({name,status:'FAIL',reason:e.message});console.error('FAIL',name,e.message);throw e;}}
const mutation=readFileSync('supabase/migrations/20261003051402_actual_use_required_progress_delta.sql','utf8');
try{
 await db.query('insert into auth.users(id) values($1),($2)',[T,U]);
 for(const[c,t,code]of[[C,T,'SYNTHETIC'],[D,U,'OTHER']]){await db.query('insert into sb_classes(id,teacher_id,name,class_code) values($1,$2,$3,$4)',[c,t,'ZZ_SYNTHETIC_CATALOG',code]);for(let l=1;l<=12;l++)await db.query('insert into sb_lesson_settings(class_id,lesson,locked) values($1,$2,false)',[c,l]);}
 for(const[i,s]of S.entries())await db.query('insert into sb_students(id,class_id,name,student_no,pin_hash) values($1,$2,$3,$4,$5)',[s,i===3?D:C,'합성학생'+(i+1),i+1,await security.hashPin(s,'8642')]);
 for(const[i,p]of P.entries())await db.query(`insert into sb_problems(id,class_id,lesson,order_index,problem_type,title,answer,code) values($1,null,1,$2,'COUNT','합성 문항',$3,$4)`,[p,[2,1,3][i],{kind:'count',value:3},'SYNTH-'+i]);
 const oldOutcome={wrongCount:0,hintShown:false,answerRevealed:false,completed:true,stars:2,xp:10};
 await db.query('select sb_record_attempt($1,$2,0,$3,null)',[S[1],P[0],oldOutcome]);
 assert.equal((await db.query('select completed from sb_student_progress where student_id=$1',[S[1]])).rows[0].completed,false,'old all-active denominator reproduced');
 await db.query(`insert into sb_projects(student_id,class_id,building_name,reason,description,layer_notes,blocks,block_appearance,intro_theme,grid_width,grid_depth,max_height,version) values($1,$2,'합성 기존 작품','보존','보존',$3,$4,$5,'museum',8,8,3,3)`,[S[1],C,['첫째','둘째','셋째'],[{x:7,y:0,z:7}],{'7,0,7':'brick'}]);
 await db.query('insert into sb_student_pin_vault(student_id,class_id,pin_plain) values($1,$2,$3)',[S[1],C,'8642']);
 await check('기존 assignment touch 누락 열 오류 재현',async()=>{await db.query(`insert into sb_practice_assignments(installation_id,class_id,student_id,lesson,curriculum_version,set_id,seed,target_total) values('synthetic',$1,$2,12,'v1','legacy',7,5)`,[C,S[1]]);await assert.rejects(db.query("update sb_practice_assignments set active=false where installation_id='synthetic'"),/has no field.*updated_at/);});
 const before=await snapshot(db);const protectedTables=catalog.tables.map(t=>t.name).filter(t=>t!=='sb_student_progress');
 async function protectedRows(){return Object.fromEntries(await Promise.all(protectedTables.map(async t=>[t,(await db.query(`select to_jsonb(t) r from ${t} t order by to_jsonb(t)::text`)).rows.map(row=>{if(t==='sb_practice_assignments')delete row.r.updated_at;return row;})])));}
 const countBefore=(await db.exec(readFileSync('backfill-aggregate.sql','utf8'))).find(r=>r.rows?.[0]?.aggregate)?.rows[0].aggregate;assert.equal(countBefore.total_changed_rows,2); const saved=await protectedRows();const oldProgress=(await db.query('select * from sb_student_progress order by student_id,lesson')).rows;await db.exec(mutation);const after=await snapshot(db);
 await check('catalog/권한/RLS/기존 데이터 보존',async()=>{assert.deepEqual(await protectedRows(),saved);for(const old of oldProgress){const now=(await db.query('select * from sb_student_progress where student_id=$1 and lesson=$2',[old.student_id,old.lesson])).rows[0];for(const k of Object.keys(old).filter(k=>!['completed','completed_at'].includes(k)))assert.deepEqual(now[k],old[k],'original progress '+k);if(old.completed)assert.equal(now.completed,true);}for(const k of['tables','constraints','indexes','policies','policy_modes','column_acls'])assert.deepEqual(after[k],before[k],k+' unchanged');assert.deepEqual(after.columns.filter(c=>!(c.table==='sb_practice_assignments'&&c.name==='updated_at')),before.columns); const newCol=after.columns.find(c=>c.table==='sb_practice_assignments'&&c.name==='updated_at');assert.equal(newCol.type,'timestamptz');assert.equal(newCol.default,'now()');assert.equal(newCol.nullable,'NO'); const existing=after.triggers.filter(t=>t.name!=='sb_track_challenge_author');assert.deepEqual(existing,before.triggers);const changed=before.rpcs.filter(f=>after.rpcs.find(g=>g.name===f.name).definition_md5!==f.definition_md5).map(f=>f.name);assert.deepEqual(changed,['sb_record_attempt','sb_save_building','sb_submit_challenge_v2']);});
 await check('historical backfill/aggregate 일치/재실행 멱등',async()=>{const countAfter=(await db.exec(readFileSync('backfill-aggregate.sql','utf8'))).find(r=>r.rows?.[0]?.aggregate)?.rows[0].aggregate;assert.equal(countAfter.total_changed_rows,0);let r=(await db.query('select * from sb_student_progress where student_id=$1 and lesson=1',[S[1]])).rows[0];assert.equal(r.completed,true);assert.ok(r.completed_at);assert.deepEqual(await protectedRows(),saved);const p=(await db.query('select * from sb_student_progress order by student_id,lesson')).rows;await db.exec(mutation);assert.deepEqual((await db.query('select * from sb_student_progress order by student_id,lesson')).rows,p);});
 await check('teacher ownership/RLS/서비스 RPC 권한',async()=>{await db.exec('begin');await db.exec('set local role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[U]);assert.equal((await db.query('select * from sb_classes where id=$1',[C])).rows.length,0);assert.equal((await db.query('select * from sb_projects where student_id=$1',[S[1]])).rows.length,0);await db.exec('rollback');for(const f of after.rpcs.filter(f=>['sb_record_attempt','sb_save_building','sb_submit_challenge_v2','sb_reset_class_progress'].includes(f.name))){assert.ok(f.acl.includes('service_role=X/postgres'));assert.ok(!f.acl.some(a=>a.startsWith('anon=')||a.startsWith('authenticated=')||a.startsWith('=')));}});
 await db.exec('set role service_role');
 await check('새 API 교사 소유권/누락 인증',async()=>{assert.equal((await req(api,{action:'teacher:progress:summary',classId:C},{Authorization:'Bearer SYNTHETIC_OTHER'})).status,403);assert.equal((await req(api,{action:'teacher:progress:summary',classId:C})).status,401);const r=await req(api,{action:'teacher:progress:summary',classId:C},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.body.students.find(s=>s.studentId===S[1]).requiredProgress.completedLessons,1);});
 let token;
 await check('기존 student-auth 로그인/세션 검증',async()=>{assert.equal((await req(auth,{classCode:'SYNTHETIC',name:'합성학생1',pin:'9990'})).status,401);const r=await req(auth,{classCode:'synthetic',name:'합성학생1',pin:'8642'});assert.equal(r.status,200,JSON.stringify(r));token=r.body.token;assert.equal((await req(api,{action:'home'})).status,401);assert.equal((await req(api,{action:'home'},{'x-student-token':token+'tamper'})).status,401);assert.equal((await req(api,{action:'home'},{'x-student-token':token})).status,200);});
 const headers=()=>({'x-student-token':token});const student=(b)=>req(api,b,headers());
 await check('필수 0→1 / 선택 연습 분리 / rewards',async()=>{let home=await student({action:'home'});assert.equal(home.body.student.lessons[0].completed,false);assert.equal((await student({action:'attempt',problemId:P[2],submission:{kind:'count',value:3}})).body.grade.completed,true);home=await student({action:'home'});assert.equal(home.body.student.lessons[0].completed,false);const xp=(await db.query('select total_xp from sb_student_rewards where student_id=$1',[S[0]])).rows[0].total_xp;assert.ok(xp>0);const r=await student({action:'attempt',problemId:P[0],submission:{kind:'count',value:3}});assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.body.grade.correct,true);home=await student({action:'home'});assert.equal(home.body.student.lessons[0].completed,true);assert.equal(home.body.student.lessons.filter(l=>l.completed).length,1);const t=await req(api,{action:'teacher:progress:summary',classId:C},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(t.body.students.find(s=>s.studentId===S[0]).requiredProgress.completedLessons,1);const reward=await student({action:'rewards'});assert.equal(reward.status,200);assert.ok((await db.query('select total_xp from sb_student_rewards where student_id=$1',[S[0]])).rows[0].total_xp>xp);});
 const blocks=Array.from({length:5},(_,x)=>[{x,y:0,z:0},{x,y:1,z:0}]).flat();
 await check('9차시 실제 route/v2/hint/완료/중복/자기 문제 차단',async()=>{const created=await student({action:'activity:challenge:create',type:'heightMap',blocks});assert.equal(created.status,200,JSON.stringify(created));assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=9',[S[0]])).rows[0].completed,false);assert.equal((await student({action:'activity:challenge:get',code:created.body.code})).status,403);const c=(await db.query(`insert into sb_shared_challenges(class_id,author_id,share_code,source,challenge_type,blocks) values($1,$2,'SYNTHC9','student','heightMap',$3) returning id`,[C,S[2],blocks])).rows[0];const hint=await student({action:'activity:challenge:hint',code:'SYNTHC9'});assert.equal(hint.status,200,JSON.stringify(hint));assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=9',[S[0]])).rows[0].completed,false);const r=await student({action:'activity:challenge:attempt',code:'SYNTHC9',blocks});assert.equal(r.status,200,JSON.stringify(r));assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=9',[S[0]])).rows[0].completed,true);const solves=(await db.query('select * from sb_challenge_solves where student_id=$1 and challenge_id=$2',[S[0],c.id])).rows[0];assert.equal(solves.score,1);await student({action:'activity:challenge:attempt',code:'SYNTHC9',blocks});assert.deepEqual((await db.query('select * from sb_challenge_solves where student_id=$1 and challenge_id=$2',[S[0],c.id])).rows[0],solves);});
 const building={building_name:'합성 수학관',reason:'층별 비교',description:'세 층 구조',layer_notes:['첫째층','둘째층','셋째층'],blocks:[{x:0,y:0,z:0},{x:0,y:1,z:0},{x:0,y:2,z:0}],submitted:false,version:0};
 await check('10/11차시 draft/submit/CAS/신규 10×10',async()=>{let r=await student({action:'activity:project:save',lesson:10,building});assert.equal(r.status,200,JSON.stringify(r));let p=(await db.query('select * from sb_projects where student_id=$1',[S[0]])).rows[0];assert.equal(p.grid_width,10);assert.equal(p.grid_depth,10);assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=10',[S[0]])).rows[0].completed,false);assert.equal((await student({action:'activity:project:save',lesson:11,building})).status,409);r=await student({action:'activity:project:save',lesson:11,building:{...building,version:1,submitted:true}});assert.equal(r.status,200,JSON.stringify(r));assert.equal((await db.query('select count(*) n from sb_student_progress where student_id=$1 and lesson in(10,11) and completed',[S[0]])).rows[0].n,2);});
 await check('기존 project/grid/appearance/theme/ID 보존/권한',async()=>{const old=saved.sb_projects[0].r;const result=await db.query('select sb_save_building($1,$2,3,$3) version',[S[1],C,{building_name:old.building_name,reason:old.reason,description:old.description,layer_notes:old.layer_notes,blocks:old.blocks,submitted:false}]);assert.equal(result.rows[0].version,4);const p=(await db.query('select * from sb_projects where student_id=$1',[S[1]])).rows[0];for(const k of['project_id','grid_width','grid_depth','max_height','blocks','block_appearance','intro_theme'])assert.deepEqual(p[k],old[k],k);await assert.rejects(db.query('select sb_save_building($1,$2,4,$3)',[S[1],D,{}]),/FORBIDDEN_STUDENT/);});
 await check('loadout XP 제한/기존 보상',async()=>{await assert.rejects(db.query('select sb_set_reward_loadout($1,$2,$3)',[S[0],'tile','sky']),/REWARD_LOCKED/);const r=await student({action:'rewards:equip',material:'wood',theme:'blueprint'});assert.equal(r.status,200,JSON.stringify(r));});
 await check('재로그인/이전 세션 보존',async()=>{const r=await req(auth,{classCode:'SYNTHETIC',name:'합성학생1',pin:'8642'});assert.equal(r.status,200);assert.equal((await student({action:'home'})).status,200);token=r.body.token;const home=await student({action:'home'});assert.equal(home.body.student.lessons.filter(l=>l.completed).length,4);});
 await check('Phase5 assignment/attempt/reflection 계약과 기존 touch',async()=>{const assignment=await student({action:'practice-set:get-or-create',installationId:'synthetic',lesson:12,curriculumVersion:'v1',seed:31,targetTotal:5,problemIds:['synthetic-p']});assert.equal(assignment.status,200,JSON.stringify(assignment));const second=await student({action:'practice-set:get-or-create',installationId:'synthetic',lesson:12,curriculumVersion:'v1',seed:999,targetTotal:5});assert.equal(second.body.assignment.set_id,assignment.body.assignment.set_id);await db.query('update sb_practice_assignments set active=false where installation_id=$1 and student_id=$2 and set_id=$3',['synthetic',S[0],assignment.body.assignment.set_id]);const a=(await db.query('select updated_at from sb_practice_assignments where installation_id=$1 and student_id=$2 and set_id=$3',['synthetic',S[0],assignment.body.assignment.set_id])).rows[0];assert.ok(a.updated_at);const progress=await student({action:'attempt:save',installationId:'synthetic',lesson:12,curriculumVersion:'v1',stage:'solve',setId:'synthetic-set',problemId:'synthetic-p',questionIndex:0,attemptCount:1,firstAttemptResult:'correct',finalResult:'correct'});assert.equal(progress.status,200,JSON.stringify(progress)); const reflection=await student({action:'reflection:save',installationId:'synthetic',lesson:12,curriculumVersion:'v1',confidence:4,favoriteConcept:'합성',selfPraise:'합성'});assert.equal(reflection.status,200,JSON.stringify(reflection));const read=await student({action:'reflection:get',installationId:'synthetic',lesson:12,curriculumVersion:'v1'});assert.equal(read.status,200);assert.ok(read.body.reflection);});
 await check('학생간 진도·세션·작품 격리',async()=>{const r=await req(auth,{classCode:'SYNTHETIC',name:'합성학생3',pin:'8642'});assert.equal(r.status,200);const other={'x-student-token':r.body.token};const home=await req(api,{action:'home'},other);assert.equal(home.status,200);assert.equal(home.body.student.lessons[0].completed,false);assert.equal(home.body.student.lessons[9].completed,false);const own=(await db.query('select * from sb_student_progress where student_id=$1 order by lesson',[S[0]])).rows;const work=await req(api,{action:'attempt',problemId:P[2],submission:{kind:'count',value:3}},other);assert.equal(work.status,200);assert.deepEqual((await db.query('select * from sb_student_progress where student_id=$1 order by lesson',[S[0]])).rows,own);});
 await check('12차시 필수 완료/선택 자기평가·성찰 분리',async()=>{const r=await req(auth,{classCode:'SYNTHETIC',name:'합성학생2',pin:'8642'});assert.equal(r.status,200);const h={'x-student-token':r.body.token};const p=(await db.query(`insert into sb_problems(class_id,lesson,order_index,problem_type,title,answer,code) values(null,12,2,'COUNT','합성 12차시 필수',$1,'SYNTH12') returning id`,[{kind:'count',value:4}])).rows[0];assert.equal((await db.query('select count(*) n from sb_self_evaluations where student_id=$1',[S[1]])).rows[0].n,0);let a=await req(api,{action:'attempt',problemId:p.id,submission:{kind:'count',value:4}},h);assert.equal(a.status,200,JSON.stringify(a));assert.equal(a.body.grade.completed,true);assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=12',[S[1]])).rows[0].completed,true);assert.equal((await db.query('select count(*) n from sb_self_evaluations where student_id=$1',[S[1]])).rows[0].n,0);const third=await req(auth,{classCode:'SYNTHETIC',name:'합성학생3',pin:'8642'});const h3={'x-student-token':third.body.token};const review=await req(api,{action:'activity:review:save',confidence:3,reflection:'합성 선택 자기평가'},h3);assert.equal(review.status,200,JSON.stringify(review));assert.equal((await req(api,{action:'activity:review:get'},h3)).status,200);assert.equal((await req(api,{action:'reflection:save',installationId:'synthetic',lesson:12,curriculumVersion:'v1',confidence:3,selfPraise:'합성'},h3)).status,200);assert.equal((await db.query('select count(*) n from sb_student_progress where student_id=$1 and lesson=12 and completed',[S[2]])).rows[0].n,0);assert.equal((await req(api,{action:'home'},h3)).body.student.lessons[11].completed,false);});
 await check('인증 lockout/disabled/revoked/expired 경계',async()=>{for(let i=0;i<4;i++)assert.equal((await req(auth,{classCode:'SYNTHETIC',name:'합성학생3',pin:'9990'})).status,401);assert.equal((await req(auth,{classCode:'SYNTHETIC',name:'합성학생3',pin:'9990'})).status,423);assert.equal((await req(auth,{classCode:'SYNTHETIC',name:'합성학생3',pin:'8642'})).status,423);await db.query("update sb_students set status='disabled' where id=$1",[S[0]]);assert.equal((await student({action:'home'})).status,403);await db.query("update sb_students set status='active' where id=$1",[S[0]]);const hash=await security.hashToken(token);await db.query('update sb_student_sessions set revoked=true where token_hash=$1',[hash]);assert.equal((await student({action:'home'})).status,401);await db.query("update sb_student_sessions set revoked=false,expires_at=now()-interval '1 second' where token_hash=$1",[hash]);assert.equal((await student({action:'home'})).status,401);await db.query("update sb_student_sessions set expires_at=now()+interval '1 hour' where token_hash=$1",[hash]);assert.equal((await student({action:'home'})).status,200);});
 await check('class reset 소유권/범위/원자성/인증·타학급 보존',async()=>{await db.query(`insert into sb_lesson_progress_records(installation_id,class_id,student_id,curriculum_version,lesson,stage,set_id,problem_id,question_index) values('synthetic',$1,$2,'v1',1,'solve','s','p',0)`,[C,S[0]]);await db.query('select sb_record_attempt($1,$2,0,$3,null)',[S[3],P[0],oldOutcome]);const outside=(await db.query('select * from sb_problem_attempts where student_id=$1',[S[3]])).rows;const sessions=(await db.query('select * from sb_student_sessions')).rows;const pins=(await db.query('select * from sb_student_pin_vault')).rows;assert.equal((await req(api,{action:'teacher:progress:reset-class',classId:C,lesson:1},{Authorization:'Bearer SYNTHETIC_OTHER'})).status,403);assert.equal((await req(api,{action:'teacher:progress:reset-class',classId:C,lesson:13},{Authorization:'Bearer SYNTHETIC_OWNER'})).status,400);
 // Force a mid-RPC failure; deletions before it must roll back.
 await db.exec('reset role');await db.exec(`create function synthetic_fail() returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_MID_RESET_FAILURE';end$$;create trigger synthetic_fail before delete on sb_lesson_progress_records for each row execute function synthetic_fail();set role service_role`);const pre=(await db.query('select * from sb_problem_attempts order by id')).rows;const fail=await req(api,{action:'teacher:progress:reset-class',classId:C,lesson:1},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(fail.status,500);assert.deepEqual((await db.query('select * from sb_problem_attempts order by id')).rows,pre);await db.exec('reset role;drop trigger synthetic_fail on sb_lesson_progress_records;set role service_role');const r=await req(api,{action:'teacher:progress:reset-class',classId:C,lesson:1},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.body.targetedCount,3);assert.equal((await db.query('select count(*) n from sb_lesson_progress_records where class_id=$1 and lesson=1',[C])).rows[0].n,0);assert.deepEqual((await db.query('select * from sb_problem_attempts where student_id=$1',[S[3]])).rows,outside);assert.deepEqual((await db.query('select * from sb_student_sessions')).rows,sessions);assert.deepEqual((await db.query('select * from sb_student_pin_vault')).rows,pins);assert.equal((await db.query('select count(*) n from sb_projects where class_id=$1',[C])).rows[0].n,2);});
 await check('class reset 10↔11 묶음/전체 초기화/문제·인증 보존',async()=>{const challenges=(await db.query('select * from sb_shared_challenges order by id')).rows;const students=(await db.query('select * from sb_students order by id')).rows;const pins=(await db.query('select * from sb_student_pin_vault')).rows;const sessions=(await db.query('select * from sb_student_sessions')).rows;const r=await req(api,{action:'teacher:progress:reset-class',classId:C,lesson:10},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(r.status,200);assert.equal((await db.query('select count(*) n from sb_projects where class_id=$1',[C])).rows[0].n,0);assert.equal((await db.query('select count(*) n from sb_student_progress where student_id=$1 and lesson in(10,11)',[S[0]])).rows[0].n,0);assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=9',[S[0]])).rows[0].completed,true);const all=await req(api,{action:'teacher:progress:reset-class',classId:C},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(all.status,200);for(const t of ['sb_student_progress','sb_problem_attempts','sb_lesson_progress_records','sb_practice_assignments','sb_student_lesson_reflections','sb_challenge_solves'])assert.equal((await db.query(`select count(*) n from ${t} where student_id in($1,$2,$3)`,S.slice(0,3))).rows[0].n,0,t);assert.deepEqual((await db.query('select * from sb_shared_challenges order by id')).rows,challenges);assert.deepEqual((await db.query('select * from sb_students order by id')).rows,students);assert.deepEqual((await db.query('select * from sb_student_pin_vault')).rows,pins);assert.deepEqual((await db.query('select * from sb_student_sessions')).rows,sessions);assert.equal((await student({action:'home'})).status,200);});
 await check('실사용 API 원본과 신규 DB의 이전 프런트 계약',async()=>{await db.exec('set role service_role');await import('./rollback-smoke/index.ts');const oldApi=served;const teacher=await req(oldApi,{action:'teacher:progress:summary',classId:C},{Authorization:'Bearer SYNTHETIC_OWNER'});assert.equal(teacher.status,200,JSON.stringify(teacher));assert.equal((await req(oldApi,{action:'home'},headers())).status,200);const attempt=await req(oldApi,{action:'attempt',problemId:P[0],submission:{kind:'count',value:3}},headers());assert.equal(attempt.status,200,JSON.stringify(attempt));assert.equal((await db.query('select completed from sb_student_progress where student_id=$1 and lesson=1',[S[0]])).rows[0].completed,true);const oldPayload={...building,version:0};const project=await req(oldApi,{action:'activity:project:save',lesson:10,building:oldPayload},headers());assert.equal(project.status,200,JSON.stringify(project));assert.equal((await db.query('select grid_width from sb_projects where student_id=$1',[S[0]])).rows[0].grid_width,10);});
 await check('최초 적용 중간 실패/schema·모든 row 완전 rollback',async()=>{const fresh=await createFixture();try{await fresh.query('insert into auth.users values($1)',[T]);await fresh.query("insert into sb_classes(id,teacher_id,name,class_code) values($1,$2,'ZZ_SYNTHETIC_FAILURE','FAILURE')",[C,T]);await fresh.query("insert into sb_students(id,class_id,name,pin_hash) values($1,$2,'합성','synthetic-hash')",[S[0],C]);const before=await snapshot(fresh);const allRows=async()=>Object.fromEntries(await Promise.all(catalog.tables.map(async t=>[t.name,(await fresh.query(`select to_jsonb(t) r from public.${t.name} t order by to_jsonb(t)::text`)).rows])));const rows=await allRows();const bad=mutation.replace('commit;',`insert into public.sb_student_progress(student_id,lesson) values('${S[0]}',1); select 1/0; commit;`);await assert.rejects(fresh.exec(bad),/division by zero/);await fresh.exec('rollback');const after=await snapshot(fresh);for(const x of[before,after])delete x.captured_at;assert.deepEqual(after,before);assert.deepEqual(await allRows(),rows);assert.equal(after.columns.some(c=>c.table==='sb_practice_assignments'&&c.name==='updated_at'),false);assert.equal(after.rpcs.some(f=>f.name==='sb_reset_class_progress'),false);}finally{await fresh.close();}});
 await check('migration 실패 전체 rollback',async()=>{await db.exec('reset role');const before=await snapshot(db);await assert.rejects(db.exec(mutation.replace('commit;','select 1/0; commit;')),/division by zero/);await db.exec('rollback');const after=await snapshot(db);delete before.captured_at;delete after.captured_at;assert.deepEqual(after,before);});
} catch(e){console.error(e.stack?.split('\n').slice(0,4).join('\n'));process.exitCode=1;} finally{writeFileSync('evidence/synthetic-smoke.json',JSON.stringify({fixture:'current-catalog.json; no historical migration replay',handlerSource:'PR4 5a90a242; db.ts transport/provider stub only',scope:'local synthetic; NOT live authentication smoke',tests},null,2));await db.close();}
