import test from 'node:test';
import assert from 'node:assert/strict';
import { solveProjectionConstraints as solve, analyzeSolutions, validatedHeightBlocks,validatedLayerBlocks,type ProjectionConstraints } from '../shared/problems/solvers/projection.ts';
import { project,validStructure,toHeightMap,toLayers } from '../shared/blocks.ts';
const grid={gridWidth:2,gridDepth:2,maxHeight:2},all=[[true,true],[true,true]];
const multi:ProjectionConstraints={grid,projections:{top:all,front:all,side:all}};
function complete(c:ProjectionConstraints){return analyzeSolutions(c);}
test('S01/S09 full profiles on one column have one model',()=>{const r=complete({grid:{gridWidth:1,gridDepth:1,maxHeight:2},projections:{top:[[true]],front:[[true],[true]],side:[[true],[true]]}});assert.equal(r.solutionCount,1);assert.deepEqual(r.uniqueCubeCounts,[2]);});
test('S02 multiple models with the same count remain distinct',()=>{const r=complete({...multi,exactCount:6});assert.equal(r.solutionCount,2);assert.equal(r.isShapeUnique,false);assert.equal(r.isCountDeterminable,true);});
test('S03/S05/S08 independently enumerated seven 2x2 positive profiles',()=>{const r=complete(multi);assert.equal(r.solutionCount,7);assert.deepEqual(r.uniqueCubeCounts,[6,7,8]);assert.equal(r.minCubeCount,6);assert.equal(r.maxCubeCount,8);assert.equal(r.isCountDeterminable,false);assert.deepEqual(r.representativeSolutions.map(b=>b.length),[6,8]);});
test('S04 contradiction is zero solutions, never determinable',()=>{const r=solve({grid:{gridWidth:1,gridDepth:1,maxHeight:2},projections:{top:[[true]],front:[[true],[false]],side:[[true],[true]]}});assert.equal(r.status,'COMPLETE');if(r.status==='COMPLETE'){assert.equal(r.solutionCount,0);assert.equal(r.minCubeCount,null);assert.equal(r.isCountDeterminable,false);}});
test('S06 top only and S07 top plus front',()=>{assert.equal(complete({grid,projections:{top:all}}).solutionCount,16);assert.equal(complete({grid,projections:{top:all,front:all}}).solutionCount,9);});
test('S10 exact count refines to unique',()=>assert.equal(complete({...multi,exactCount:8}).solutionCount,1));
test('S11 fixed asymmetric right profile and S12 project agreement',()=>{const c:ProjectionConstraints={grid:{gridWidth:2,gridDepth:2,maxHeight:3},heights:[[2,0],[1,3]],projections:{side:[[true,true],[true,true],[true,false]]}};const r=complete(c);assert.equal(r.solutionCount,1);assert.deepEqual(project(r.representativeSolutions[0],c.grid).side,[[true,true],[true,true],[true,false]]);assert.equal(solve({...c,projections:{side:[[true,true],[true,true],[false,true]]}}).status,'COMPLETE');const wrong=solve({...c,projections:{side:[[true,true],[true,true],[false,true]]}});if(wrong.status==='COMPLETE')assert.equal(wrong.solutionCount,0);});
test('S12/S13 all small solutions obey input and gravity with independent height-pair oracle',()=>{for(let f=0;f<=3;f++)for(let count=0;count<=6;count++){const c:ProjectionConstraints={grid:{gridWidth:1,gridDepth:2,maxHeight:3},projections:{front:Array.from({length:3},(_,y)=>[y<f])},exactCount:count};const r=solve(c);assert.equal(r.status,'COMPLETE');if(r.status!=='COMPLETE')continue;let expected=0;for(let a=0;a<=3;a++)for(let b=0;b<=3;b++)if(Math.max(a,b)===f&&a+b===count)expected++;assert.equal(r.solutionCount,expected);for(const b of r.representativeSolutions){assert.ok(validStructure(b,c.grid));assert.deepEqual(project(b,c.grid).front,c.projections!.front);}}});
test('node/time/cancel budgets cannot claim uniqueness',()=>{assert.equal(solve(multi,{maxNodes:1}).status,'LIMIT_REACHED');assert.equal(solve(multi,{deadlineMs:-1}).status,'LIMIT_REACHED');const a=new AbortController();a.abort();assert.equal(solve(multi,{signal:a.signal}).status,'CANCELLED');});
test('invalid bounds, height/layer shape, floating layers and duplicates rejected',()=>{assert.equal(solve({grid:{gridWidth:10,gridDepth:10,maxHeight:3}}).status,'INVALID');assert.throws(()=>validatedHeightBlocks(grid,[[1.5,0],[0,0]]));assert.throws(()=>validatedLayerBlocks(grid,[[[true,false],[false,false]],[[false,true],[false,false]]]));assert.equal(solve({grid,givenBlocks:[{x:0,y:0,z:0},{x:0,y:0,z:0}]}).status,'INVALID');});
test('height and layer round trips with fixed count and middle-layer inference',()=>{const g={...grid,maxHeight:3},b=validatedHeightBlocks(g,[[2,0],[1,3]]);assert.equal(b.length,6);assert.deepEqual(toHeightMap(b,g),[[2,0],[1,3]]);assert.deepEqual(validatedLayerBlocks(g,toLayers(b,g)),b);const r=complete({grid:{gridWidth:2,gridDepth:1,maxHeight:3},layers:[[[true,true]],null,[[true,false]]]});assert.equal(r.solutionCount,2);assert.deepEqual(r.uniqueCubeCounts,[4,5]);});
test('given visible block forces its supporting column without inventing other restrictions',()=>{const r=complete({grid:{gridWidth:1,gridDepth:1,maxHeight:3},givenBlocks:[{x:0,y:1,z:0}]});assert.deepEqual(r.uniqueCubeCounts,[2,3]);});
